// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.2
// source: protoapi.proto

package protoapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RandomClient is the client API for Random service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RandomClient interface {
	// Return date and time to the client
	GetDate(ctx context.Context, in *GetDateRequest, opts ...grpc.CallOption) (*GetDateResponse, error)
	// Return random integer to the client
	GetRandomInt(ctx context.Context, in *GetRandomIntRequest, opts ...grpc.CallOption) (*GetRandomIntResponse, error)
	// Return randomly generated password of the given length
	GetRandomPass(ctx context.Context, in *GetRandomPassRequest, opts ...grpc.CallOption) (*GetRandomPassResponse, error)
}

type randomClient struct {
	cc grpc.ClientConnInterface
}

func NewRandomClient(cc grpc.ClientConnInterface) RandomClient {
	return &randomClient{cc}
}

func (c *randomClient) GetDate(ctx context.Context, in *GetDateRequest, opts ...grpc.CallOption) (*GetDateResponse, error) {
	out := new(GetDateResponse)
	err := c.cc.Invoke(ctx, "/Random/GetDate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *randomClient) GetRandomInt(ctx context.Context, in *GetRandomIntRequest, opts ...grpc.CallOption) (*GetRandomIntResponse, error) {
	out := new(GetRandomIntResponse)
	err := c.cc.Invoke(ctx, "/Random/GetRandomInt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *randomClient) GetRandomPass(ctx context.Context, in *GetRandomPassRequest, opts ...grpc.CallOption) (*GetRandomPassResponse, error) {
	out := new(GetRandomPassResponse)
	err := c.cc.Invoke(ctx, "/Random/GetRandomPass", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RandomServer is the server API for Random service.
// All implementations must embed UnimplementedRandomServer
// for forward compatibility
type RandomServer interface {
	// Return date and time to the client
	GetDate(context.Context, *GetDateRequest) (*GetDateResponse, error)
	// Return random integer to the client
	GetRandomInt(context.Context, *GetRandomIntRequest) (*GetRandomIntResponse, error)
	// Return randomly generated password of the given length
	GetRandomPass(context.Context, *GetRandomPassRequest) (*GetRandomPassResponse, error)
	mustEmbedUnimplementedRandomServer()
}

// UnimplementedRandomServer must be embedded to have forward compatible implementations.
type UnimplementedRandomServer struct {
}

func (UnimplementedRandomServer) GetDate(context.Context, *GetDateRequest) (*GetDateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDate not implemented")
}
func (UnimplementedRandomServer) GetRandomInt(context.Context, *GetRandomIntRequest) (*GetRandomIntResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRandomInt not implemented")
}
func (UnimplementedRandomServer) GetRandomPass(context.Context, *GetRandomPassRequest) (*GetRandomPassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRandomPass not implemented")
}
func (UnimplementedRandomServer) mustEmbedUnimplementedRandomServer() {}

// UnsafeRandomServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RandomServer will
// result in compilation errors.
type UnsafeRandomServer interface {
	mustEmbedUnimplementedRandomServer()
}

func RegisterRandomServer(s grpc.ServiceRegistrar, srv RandomServer) {
	s.RegisterService(&Random_ServiceDesc, srv)
}

func _Random_GetDate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RandomServer).GetDate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Random/GetDate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RandomServer).GetDate(ctx, req.(*GetDateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Random_GetRandomInt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRandomIntRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RandomServer).GetRandomInt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Random/GetRandomInt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RandomServer).GetRandomInt(ctx, req.(*GetRandomIntRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Random_GetRandomPass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRandomPassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RandomServer).GetRandomPass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Random/GetRandomPass",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RandomServer).GetRandomPass(ctx, req.(*GetRandomPassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Random_ServiceDesc is the grpc.ServiceDesc for Random service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Random_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Random",
	HandlerType: (*RandomServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDate",
			Handler:    _Random_GetDate_Handler,
		},
		{
			MethodName: "GetRandomInt",
			Handler:    _Random_GetRandomInt_Handler,
		},
		{
			MethodName: "GetRandomPass",
			Handler:    _Random_GetRandomPass_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protoapi.proto",
}
